apiVersion: v1
kind: Service
metadata:
  name: websocket
spec:
  type: LoadBalancer
  ports:
  - name: websocket
    port: 80
    targetPort: "websocket-port"
    protocol: TCP
  selector:
    app: websocket