# docker-compose.yml
version: '3.1'

services:

  payment-service:
    build: ./payment-service
    network_mode: "host"
    ports:
    - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://gcic:dreamer6@ds163330.mlab.com:63330/invest"
      STRIPE_KEY: "sk_test_0R7KtTokmbmUk1sK2qqdyi6y"
      DISABLE_AUTH: "true"

  user-service:
    build: ./user-service
    network_mode: "host"
    ports:
    - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://gcic:dreamer6@ds163330.mlab.com:63330/invest"
      DISABLE_AUTH: "true"

  plan-service:
    build: ./plan-service
    network_mode: "host"
    ports:
    - 50054:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://gcic:dreamer6@ds163330.mlab.com:63330/invest"
      DISABLE_AUTH: "true"

  partner-service:
    build: ./partner-service
    network_mode: "host"
    ports:
    - 50055:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://gcic:dreamer6@ds163330.mlab.com:63330/invest"
      DISABLE_AUTH: "true"

  benefit-service:
    build: ./benefit-service
    network_mode: "host"
    ports:
    - 50056:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://gcic:dreamer6@ds163330.mlab.com:63330/invest"
      DISABLE_AUTH: "true"

  chat-service:
    build: ./chat-service
    network_mode: "host"
    ports:
    - 50057:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://gcic:dreamer6@ds163330.mlab.com:63330/invest"
      DISABLE_AUTH: "true"