// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chat/chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Img                  string   `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Users                []*User    `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "chat.Message")
	proto.RegisterType((*User)(nil), "chat.User")
	proto.RegisterType((*Error)(nil), "chat.Error")
	proto.RegisterType((*Response)(nil), "chat.Response")
	proto.RegisterType((*Request)(nil), "chat.Request")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ChatService service

type ChatServiceClient interface {
	Online(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Messages(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
}

type chatServiceClient struct {
	c           client.Client
	serviceName string
}

func NewChatServiceClient(serviceName string, c client.Client) ChatServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chat"
	}
	return &chatServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *chatServiceClient) Online(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ChatService.Online", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Messages(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ChatService.Messages", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ChatService service

type ChatServiceHandler interface {
	Online(context.Context, *Request, *Response) error
	Messages(context.Context, *User, *Response) error
}

func RegisterChatServiceHandler(s server.Server, hdlr ChatServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ChatService{hdlr}, opts...))
}

type ChatService struct {
	ChatServiceHandler
}

func (h *ChatService) Online(ctx context.Context, in *Request, out *Response) error {
	return h.ChatServiceHandler.Online(ctx, in, out)
}

func (h *ChatService) Messages(ctx context.Context, in *User, out *Response) error {
	return h.ChatServiceHandler.Messages(ctx, in, out)
}

func init() { proto.RegisterFile("proto/chat/chat.proto", fileDescriptor_411570473cc66b06) }

var fileDescriptor_411570473cc66b06 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdf, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xbf, 0xeb, 0xda, 0xad, 0xbd, 0xe5, 0x3b, 0x24, 0x20, 0x04, 0x45, 0x28, 0x79, 0xaa,
	0x2f, 0x13, 0xe6, 0xb3, 0x4f, 0xe2, 0xe3, 0x14, 0x23, 0xe2, 0xa3, 0x64, 0xed, 0xdd, 0x16, 0x58,
	0x9b, 0x9a, 0x64, 0xe2, 0x9f, 0x2f, 0xf9, 0x51, 0x19, 0xec, 0xa5, 0x9c, 0x9c, 0xf3, 0xe1, 0x9e,
	0xf4, 0x06, 0x2e, 0x07, 0xad, 0xac, 0xba, 0x6b, 0xf6, 0xc2, 0xfa, 0xcf, 0xd2, 0x9f, 0x49, 0xea,
	0x34, 0x7b, 0x85, 0xf9, 0x1a, 0x8d, 0x11, 0x3b, 0x24, 0x0b, 0x48, 0x64, 0x4b, 0x27, 0xd5, 0xa4,
	0x2e, 0x78, 0x22, 0x5b, 0x42, 0x20, 0xdd, 0x6a, 0xd5, 0xd1, 0xc4, 0x3b, 0x5e, 0x3b, 0xc6, 0x2a,
	0x3a, 0x0d, 0x8c, 0x55, 0x8e, 0xb1, 0xf8, 0x63, 0x69, 0x1a, 0x18, 0xa7, 0x59, 0x0b, 0xe9, 0xbb,
	0x41, 0x7d, 0x36, 0xef, 0x06, 0x60, 0x2b, 0xb5, 0xb1, 0x9f, 0xbd, 0xe8, 0x30, 0x4e, 0x2d, 0xbc,
	0xf3, 0x2c, 0x3a, 0x24, 0xd7, 0x50, 0x1c, 0xc4, 0x98, 0x86, 0x86, 0xdc, 0x19, 0x3e, 0xbc, 0x80,
	0xa9, 0xec, 0x76, 0xb1, 0xc6, 0x49, 0xf6, 0x00, 0xd9, 0x93, 0xd6, 0x4a, 0xbb, 0x2b, 0x34, 0xaa,
	0x45, 0x5f, 0x94, 0x71, 0xaf, 0x49, 0x05, 0x65, 0x8b, 0xa6, 0xd1, 0x72, 0xb0, 0x52, 0xf5, 0xb1,
	0xeb, 0xd4, 0x62, 0x1f, 0x90, 0x73, 0x34, 0x83, 0xea, 0x0d, 0x92, 0x5b, 0xc8, 0xbb, 0xb0, 0x03,
	0x43, 0x27, 0xd5, 0xb4, 0x2e, 0x57, 0xff, 0x97, 0x7e, 0x51, 0x71, 0x33, 0xfc, 0x2f, 0x26, 0x15,
	0x64, 0x47, 0x83, 0xda, 0xd0, 0xc4, 0x73, 0x10, 0x38, 0xf7, 0xbb, 0x3c, 0x04, 0xac, 0x80, 0x39,
	0xc7, 0xaf, 0x23, 0x1a, 0xbb, 0xda, 0x40, 0xf9, 0xb8, 0x17, 0xf6, 0x0d, 0xf5, 0xb7, 0x6c, 0x5c,
	0xcd, 0xec, 0xa5, 0x3f, 0xc8, 0x1e, 0x49, 0x1c, 0x1f, 0xb9, 0xab, 0xc5, 0x78, 0x0c, 0xf7, 0x61,
	0xff, 0x48, 0x0d, 0xf9, 0x7a, 0xac, 0x3c, 0xe9, 0x38, 0x27, 0x37, 0x33, 0xff, 0x98, 0xf7, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x7a, 0x41, 0xdc, 0xe5, 0x01, 0x00, 0x00,
}
