apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 'client-port'
  selector:
    app: client