// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/benefit/benefit.proto

package benefit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	"gopkg.in/mgo.v2/bson"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Benefit struct {
	Id                   bson.ObjectId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Contact              string   `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	Img                  []string `protobuf:"bytes,7,rep,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Benefit) Reset()         { *m = Benefit{} }
func (m *Benefit) String() string { return proto.CompactTextString(m) }
func (*Benefit) ProtoMessage()    {}
func (*Benefit) Descriptor() ([]byte, []int) {
	return fileDescriptor_03087d0a7f82f1f4, []int{0}
}

func (m *Benefit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Benefit.Unmarshal(m, b)
}
func (m *Benefit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Benefit.Marshal(b, m, deterministic)
}
func (m *Benefit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Benefit.Merge(m, src)
}
func (m *Benefit) XXX_Size() int {
	return xxx_messageInfo_Benefit.Size(m)
}
func (m *Benefit) XXX_DiscardUnknown() {
	xxx_messageInfo_Benefit.DiscardUnknown(m)
}

var xxx_messageInfo_Benefit proto.InternalMessageInfo

func (m *Benefit) GetId() bson.ObjectId {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Benefit) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Benefit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Benefit) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Benefit) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Benefit) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *Benefit) GetImg() []string {
	if m != nil {
		return m.Img
	}
	return nil
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_03087d0a7f82f1f4, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_03087d0a7f82f1f4, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Benefit              *Benefit   `protobuf:"bytes,2,opt,name=benefit,proto3" json:"benefit,omitempty"`
	Benefits             []*Benefit `protobuf:"bytes,3,rep,name=benefits,proto3" json:"benefits,omitempty"`
	Errors               []*Error   `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_03087d0a7f82f1f4, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetBenefit() *Benefit {
	if m != nil {
		return m.Benefit
	}
	return nil
}

func (m *Response) GetBenefits() []*Benefit {
	if m != nil {
		return m.Benefits
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Benefit)(nil), "benefit.Benefit")
	proto.RegisterType((*Request)(nil), "benefit.Request")
	proto.RegisterType((*Error)(nil), "benefit.Error")
	proto.RegisterType((*Response)(nil), "benefit.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BenefitService service

type BenefitServiceClient interface {
	Create(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error)
	All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type benefitServiceClient struct {
	c           client.Client
	serviceName string
}

func NewBenefitServiceClient(serviceName string, c client.Client) BenefitServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "benefit"
	}
	return &benefitServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *benefitServiceClient) Create(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BenefitService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *benefitServiceClient) Update(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BenefitService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *benefitServiceClient) Delete(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BenefitService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *benefitServiceClient) Get(ctx context.Context, in *Benefit, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BenefitService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *benefitServiceClient) All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BenefitService.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BenefitService service

type BenefitServiceHandler interface {
	Create(context.Context, *Benefit, *Response) error
	Update(context.Context, *Benefit, *Response) error
	Delete(context.Context, *Benefit, *Response) error
	Get(context.Context, *Benefit, *Response) error
	All(context.Context, *Request, *Response) error
}

func RegisterBenefitServiceHandler(s server.Server, hdlr BenefitServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&BenefitService{hdlr}, opts...))
}

type BenefitService struct {
	BenefitServiceHandler
}

func (h *BenefitService) Create(ctx context.Context, in *Benefit, out *Response) error {
	return h.BenefitServiceHandler.Create(ctx, in, out)
}

func (h *BenefitService) Update(ctx context.Context, in *Benefit, out *Response) error {
	return h.BenefitServiceHandler.Update(ctx, in, out)
}

func (h *BenefitService) Delete(ctx context.Context, in *Benefit, out *Response) error {
	return h.BenefitServiceHandler.Delete(ctx, in, out)
}

func (h *BenefitService) Get(ctx context.Context, in *Benefit, out *Response) error {
	return h.BenefitServiceHandler.Get(ctx, in, out)
}

func (h *BenefitService) All(ctx context.Context, in *Request, out *Response) error {
	return h.BenefitServiceHandler.All(ctx, in, out)
}

func init() { proto.RegisterFile("proto/benefit/benefit.proto", fileDescriptor_03087d0a7f82f1f4) }

var fileDescriptor_03087d0a7f82f1f4 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x26, 0x49, 0x93, 0xb4, 0x57, 0xa9, 0x2a, 0x16, 0x83, 0x05, 0x4b, 0x94, 0x01, 0x55, 0xa8,
	0x6a, 0xa5, 0x32, 0x33, 0xf0, 0x27, 0x76, 0x23, 0x1e, 0x20, 0x8d, 0x0f, 0x64, 0x29, 0x8d, 0x83,
	0x6d, 0x78, 0x1e, 0x76, 0x1e, 0x12, 0x94, 0xab, 0x53, 0x55, 0x34, 0x03, 0x9d, 0xf2, 0xdd, 0xf7,
	0x93, 0x7c, 0xbe, 0x18, 0x2e, 0x1a, 0xa3, 0x9d, 0x5e, 0xae, 0xb1, 0xc6, 0x57, 0xe5, 0xba, 0xe7,
	0x82, 0x58, 0x96, 0xfa, 0x31, 0xff, 0x0e, 0x20, 0xbd, 0xdb, 0x62, 0x36, 0x81, 0x50, 0x49, 0x1e,
	0x64, 0xc1, 0x6c, 0x24, 0x42, 0x25, 0xd9, 0x19, 0xc4, 0x4e, 0xb9, 0x0a, 0x79, 0x48, 0xd4, 0x76,
	0x60, 0x0c, 0x06, 0x75, 0xb1, 0x41, 0x1e, 0x11, 0x49, 0x98, 0x65, 0x30, 0x96, 0x68, 0x4b, 0xa3,
	0x1a, 0xa7, 0x74, 0xcd, 0x07, 0x24, 0xed, 0x53, 0x8c, 0x43, 0x5a, 0x48, 0x69, 0xd0, 0x5a, 0x1e,
	0x93, 0xda, 0x8d, 0xad, 0x52, 0xea, 0xda, 0x15, 0xa5, 0xe3, 0xc9, 0x56, 0xf1, 0x23, 0x9b, 0x42,
	0xa4, 0x36, 0x6f, 0x3c, 0xcd, 0xa2, 0xd9, 0x48, 0xb4, 0x30, 0x1f, 0x41, 0x2a, 0xf0, 0xfd, 0x03,
	0xad, 0xcb, 0x6f, 0x20, 0x7e, 0x34, 0x46, 0x9b, 0xb6, 0x4f, 0xa9, 0x25, 0x52, 0xef, 0x58, 0x10,
	0xfe, 0xdb, 0x27, 0x3c, 0xe8, 0x93, 0x7f, 0x05, 0x30, 0x14, 0x68, 0x1b, 0x5d, 0x5b, 0xec, 0x7d,
	0xc5, 0x15, 0x74, 0x3b, 0xa2, 0xf8, 0x78, 0x35, 0x5d, 0x74, 0x2b, 0xf4, 0xfb, 0x12, 0x9d, 0x81,
	0xcd, 0x61, 0xe8, 0xa1, 0xe5, 0x51, 0x16, 0xf5, 0x9a, 0x77, 0x0e, 0x76, 0x09, 0x09, 0xb6, 0xcd,
	0x2d, 0x1f, 0x90, 0x77, 0xb2, 0xf3, 0xd2, 0x81, 0x84, 0x57, 0x57, 0x3f, 0x01, 0x4c, 0x7c, 0xfa,
	0x19, 0xcd, 0xa7, 0x2a, 0x91, 0x2d, 0x21, 0xb9, 0x37, 0x58, 0x38, 0x64, 0x07, 0x1f, 0x38, 0x3f,
	0xdd, 0x31, 0xdd, 0xb9, 0xf2, 0x93, 0x36, 0xf0, 0xd2, 0xc8, 0xe3, 0x02, 0x0f, 0x58, 0xe1, 0xff,
	0x03, 0x73, 0x88, 0x9e, 0xd0, 0x1d, 0xe1, 0xbe, 0xad, 0xaa, 0x3d, 0xb7, 0xff, 0x9d, 0xbd, 0xee,
	0x75, 0x42, 0x97, 0xf5, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xa5, 0xcc, 0x82, 0xcb, 0x02,
	0x00, 0x00,
}
