// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/payment/payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Charge struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Customer             string   `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Charge) Reset()         { *m = Charge{} }
func (m *Charge) String() string { return proto.CompactTextString(m) }
func (*Charge) ProtoMessage()    {}
func (*Charge) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{0}
}

func (m *Charge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Charge.Unmarshal(m, b)
}
func (m *Charge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Charge.Marshal(b, m, deterministic)
}
func (m *Charge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Charge.Merge(m, src)
}
func (m *Charge) XXX_Size() int {
	return xxx_messageInfo_Charge.Size(m)
}
func (m *Charge) XXX_DiscardUnknown() {
	xxx_messageInfo_Charge.DiscardUnknown(m)
}

var xxx_messageInfo_Charge proto.InternalMessageInfo

func (m *Charge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Charge) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Charge) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Charge) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Charge) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *Charge) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Charge) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Customer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{1}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChargeId             string   `protobuf:"bytes,3,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IdempotencyKey       string   `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Transaction) GetChargeId() string {
	if m != nil {
		return m.ChargeId
	}
	return ""
}

func (m *Transaction) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Transaction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Transaction) GetIdempotencyKey() string {
	if m != nil {
		return m.IdempotencyKey
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	Customer             *Customer      `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Charge               *Charge        `protobuf:"bytes,2,opt,name=charge,proto3" json:"charge,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Errors               *Error         `protobuf:"bytes,4,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Response) GetCharge() *Charge {
	if m != nil {
		return m.Charge
	}
	return nil
}

func (m *Response) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Response) GetErrors() *Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Charge)(nil), "payment.Charge")
	proto.RegisterType((*Customer)(nil), "payment.Customer")
	proto.RegisterType((*Transaction)(nil), "payment.Transaction")
	proto.RegisterType((*Error)(nil), "payment.Error")
	proto.RegisterType((*Response)(nil), "payment.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PaymentService service

type PaymentServiceClient interface {
	CreateCharge(ctx context.Context, in *Charge, opts ...client.CallOption) (*Response, error)
	CreateCustomer(ctx context.Context, in *Customer, opts ...client.CallOption) (*Response, error)
	History(ctx context.Context, in *Transaction, opts ...client.CallOption) (*Response, error)
}

type paymentServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPaymentServiceClient(serviceName string, c client.Client) PaymentServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "payment"
	}
	return &paymentServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *paymentServiceClient) CreateCharge(ctx context.Context, in *Charge, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.CreateCharge", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateCustomer(ctx context.Context, in *Customer, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.CreateCustomer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) History(ctx context.Context, in *Transaction, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PaymentService.History", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentService service

type PaymentServiceHandler interface {
	CreateCharge(context.Context, *Charge, *Response) error
	CreateCustomer(context.Context, *Customer, *Response) error
	History(context.Context, *Transaction, *Response) error
}

func RegisterPaymentServiceHandler(s server.Server, hdlr PaymentServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PaymentService{hdlr}, opts...))
}

type PaymentService struct {
	PaymentServiceHandler
}

func (h *PaymentService) CreateCharge(ctx context.Context, in *Charge, out *Response) error {
	return h.PaymentServiceHandler.CreateCharge(ctx, in, out)
}

func (h *PaymentService) CreateCustomer(ctx context.Context, in *Customer, out *Response) error {
	return h.PaymentServiceHandler.CreateCustomer(ctx, in, out)
}

func (h *PaymentService) History(ctx context.Context, in *Transaction, out *Response) error {
	return h.PaymentServiceHandler.History(ctx, in, out)
}

func init() { proto.RegisterFile("proto/payment/payment.proto", fileDescriptor_78ce6d11f0608d17) }

var fileDescriptor_78ce6d11f0608d17 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0xec, 0x24, 0xe3, 0xca, 0x15, 0xab, 0x08, 0xac, 0xf6, 0x12, 0xf9, 0x40, 0x73,
	0xa1, 0x48, 0xa6, 0x87, 0x5e, 0x38, 0x45, 0x20, 0x2a, 0x2e, 0x68, 0xe1, 0x5e, 0x19, 0x7b, 0x04,
	0xab, 0x62, 0xaf, 0xb5, 0xbb, 0x41, 0xf2, 0x8f, 0x21, 0x71, 0xe7, 0x0b, 0xf8, 0x22, 0xe4, 0xb1,
	0x37, 0xd9, 0x3a, 0x81, 0x93, 0xfd, 0x66, 0xe6, 0xcd, 0xce, 0x7b, 0xb3, 0x0b, 0x97, 0xad, 0x92,
	0x46, 0xbe, 0x6a, 0x8b, 0xae, 0xc6, 0xc6, 0xd8, 0xef, 0x35, 0x45, 0xd9, 0x7c, 0x84, 0xd9, 0x2f,
	0x0f, 0xa2, 0xed, 0xb7, 0x42, 0x7d, 0x45, 0x96, 0x80, 0x2f, 0xaa, 0xd4, 0x5b, 0x7b, 0x9b, 0x25,
	0xf7, 0x45, 0xc5, 0x9e, 0x41, 0x54, 0xd4, 0x72, 0xd7, 0x98, 0xd4, 0x5f, 0x7b, 0x9b, 0x80, 0x8f,
	0x88, 0x5d, 0xc0, 0xa2, 0xdc, 0x29, 0x85, 0x4d, 0xd9, 0xa5, 0x01, 0x55, 0xef, 0x31, 0x5b, 0x43,
	0x5c, 0xa1, 0x2e, 0x95, 0x68, 0x8d, 0x90, 0x4d, 0x3a, 0xa3, 0xb4, 0x1b, 0x1a, 0xd8, 0xda, 0xc8,
	0x1a, 0x55, 0x1a, 0x5a, 0xf6, 0x80, 0xd9, 0x73, 0x98, 0xef, 0x34, 0xaa, 0x7b, 0x51, 0xa5, 0x11,
	0xa5, 0xa2, 0x1e, 0xde, 0x55, 0x6c, 0x05, 0xa1, 0x91, 0x0f, 0xd8, 0xa4, 0x73, 0x0a, 0x0f, 0x20,
	0x7b, 0x07, 0x8b, 0xad, 0xa5, 0x4e, 0x87, 0x5f, 0x41, 0x88, 0x75, 0x21, 0xbe, 0xd3, 0xec, 0x4b,
	0x3e, 0x80, 0x43, 0x9f, 0xc0, 0xed, 0xf3, 0xc7, 0x83, 0xf8, 0xb3, 0x2a, 0x1a, 0x5d, 0x94, 0x34,
	0xe2, 0xb4, 0x97, 0x33, 0x96, 0xff, 0x68, 0xac, 0x4b, 0x58, 0x96, 0xe4, 0x5d, 0x9f, 0xb2, 0x56,
	0x50, 0xe0, 0xce, 0xb5, 0x6f, 0xf6, 0x4f, 0xfb, 0xc2, 0xff, 0xdb, 0x17, 0x1d, 0xdb, 0x77, 0x05,
	0xe7, 0xa2, 0xc2, 0xba, 0x95, 0xa6, 0x27, 0xdc, 0x3f, 0x60, 0x37, 0x7a, 0x92, 0x38, 0xe1, 0x0f,
	0xd8, 0x65, 0x6f, 0x20, 0x7c, 0xab, 0x94, 0x54, 0x8c, 0xc1, 0xac, 0x94, 0x15, 0x92, 0x9e, 0x90,
	0xd3, 0xff, 0xf4, 0x1c, 0xff, 0xe8, 0x9c, 0xec, 0xb7, 0x07, 0x0b, 0x8e, 0xba, 0x95, 0x8d, 0x46,
	0xf6, 0xd2, 0xd9, 0x59, 0xdf, 0x26, 0xce, 0x9f, 0x5e, 0xdb, 0xfb, 0x64, 0x37, 0xe0, 0xac, 0xf1,
	0x0a, 0xa2, 0xc1, 0x05, 0x6a, 0x1c, 0xe7, 0xe7, 0x87, 0x62, 0x0a, 0xf3, 0x31, 0xcd, 0x6e, 0xe1,
	0xcc, 0x1c, 0x7c, 0xd7, 0x69, 0xb0, 0x0e, 0x36, 0x71, 0xbe, 0xda, 0x97, 0x3b, 0x4b, 0xe1, 0x8f,
	0x2a, 0xd9, 0x0b, 0x88, 0xb0, 0x57, 0xa7, 0xc9, 0xdc, 0x38, 0x4f, 0xf6, 0x1c, 0x12, 0xcd, 0xc7,
	0x6c, 0xfe, 0xd3, 0x83, 0xe4, 0xe3, 0x90, 0xf9, 0x84, 0xea, 0x87, 0x28, 0x91, 0xdd, 0xc0, 0xd9,
	0x56, 0x61, 0x61, 0x70, 0xbc, 0xf6, 0xd3, 0xe9, 0x2e, 0x0e, 0xda, 0xac, 0x01, 0xd9, 0x13, 0x76,
	0x0b, 0xc9, 0xc8, 0xb2, 0x2a, 0x8f, 0x2d, 0x38, 0xcd, 0xbc, 0x81, 0xf9, 0x7b, 0xa1, 0x8d, 0x54,
	0x1d, 0x3b, 0xa9, 0xec, 0x24, 0xeb, 0x4b, 0x44, 0xef, 0xf4, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0x84, 0xe7, 0xe6, 0xc6, 0x03, 0x00, 0x00,
}
