apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plan
  template:
    metadata:
      labels:
        app: plan
    spec:
      containers:
      - name: plan-service
        image: eu.gcr.io/gcic-219917/plan-service:latest
        imagePullPolicy: Always
        command: [
          "./plan-service",
          "--selector=static",
          "--server_address=:8080",
        ]
        env:
        - name: DB_HOST
          value: "mongo:27017"
        - name: UPDATED_AT
          value: "Sun 19 Sep 2018 14:38:58 GMT"
        ports:
        - containerPort: 8080
          name: plan-port