// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/partner/partner.proto

package partner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	"gopkg.in/mgo.v2/bson"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Partner struct {
	Id                   *bson.ObjectId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Contact              string   `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Img                  string   `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partner) Reset()         { *m = Partner{} }
func (m *Partner) String() string { return proto.CompactTextString(m) }
func (*Partner) ProtoMessage()    {}
func (*Partner) Descriptor() ([]byte, []int) {
	return fileDescriptor_e02f55082ebf1e57, []int{0}
}

func (m *Partner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partner.Unmarshal(m, b)
}
func (m *Partner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partner.Marshal(b, m, deterministic)
}
func (m *Partner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partner.Merge(m, src)
}
func (m *Partner) XXX_Size() int {
	return xxx_messageInfo_Partner.Size(m)
}
func (m *Partner) XXX_DiscardUnknown() {
	xxx_messageInfo_Partner.DiscardUnknown(m)
}

var xxx_messageInfo_Partner proto.InternalMessageInfo

func (m *Partner) GetId() *bson.ObjectId {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Partner) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Partner) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *Partner) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e02f55082ebf1e57, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_e02f55082ebf1e57, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Partner              *Partner   `protobuf:"bytes,2,opt,name=partner,proto3" json:"partner,omitempty"`
	Partners             []*Partner `protobuf:"bytes,3,rep,name=partners,proto3" json:"partners,omitempty"`
	Errors               []*Error   `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e02f55082ebf1e57, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetPartner() *Partner {
	if m != nil {
		return m.Partner
	}
	return nil
}

func (m *Response) GetPartners() []*Partner {
	if m != nil {
		return m.Partners
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Partner)(nil), "partner.Partner")
	proto.RegisterType((*Request)(nil), "partner.Request")
	proto.RegisterType((*Error)(nil), "partner.Error")
	proto.RegisterType((*Response)(nil), "partner.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PartnerService service

type PartnerServiceClient interface {
	Create(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error)
	All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type partnerServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPartnerServiceClient(serviceName string, c client.Client) PartnerServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "partner"
	}
	return &partnerServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *partnerServiceClient) Create(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PartnerService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) Update(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PartnerService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) Delete(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PartnerService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) Get(ctx context.Context, in *Partner, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PartnerService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PartnerService.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PartnerService service

type PartnerServiceHandler interface {
	Create(context.Context, *Partner, *Response) error
	Update(context.Context, *Partner, *Response) error
	Delete(context.Context, *Partner, *Response) error
	Get(context.Context, *Partner, *Response) error
	All(context.Context, *Request, *Response) error
}

func RegisterPartnerServiceHandler(s server.Server, hdlr PartnerServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PartnerService{hdlr}, opts...))
}

type PartnerService struct {
	PartnerServiceHandler
}

func (h *PartnerService) Create(ctx context.Context, in *Partner, out *Response) error {
	return h.PartnerServiceHandler.Create(ctx, in, out)
}

func (h *PartnerService) Update(ctx context.Context, in *Partner, out *Response) error {
	return h.PartnerServiceHandler.Update(ctx, in, out)
}

func (h *PartnerService) Delete(ctx context.Context, in *Partner, out *Response) error {
	return h.PartnerServiceHandler.Delete(ctx, in, out)
}

func (h *PartnerService) Get(ctx context.Context, in *Partner, out *Response) error {
	return h.PartnerServiceHandler.Get(ctx, in, out)
}

func (h *PartnerService) All(ctx context.Context, in *Request, out *Response) error {
	return h.PartnerServiceHandler.All(ctx, in, out)
}

func init() { proto.RegisterFile("proto/partner/partner.proto", fileDescriptor_e02f55082ebf1e57) }

var fileDescriptor_e02f55082ebf1e57 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xed, 0x76, 0xb7, 0xed, 0xce, 0x42, 0x59, 0xe7, 0x14, 0xd6, 0x4b, 0xe9, 0x41, 0x44,
	0x96, 0x5d, 0x58, 0xcf, 0x1e, 0x44, 0xc5, 0xab, 0x44, 0xfc, 0x01, 0x35, 0x1d, 0x24, 0x50, 0x9b,
	0x9a, 0x44, 0x7f, 0x8f, 0xff, 0x54, 0x69, 0x4c, 0x4a, 0xc1, 0x1e, 0xdc, 0x53, 0xdf, 0xbc, 0x7c,
	0xaf, 0xd3, 0x47, 0x03, 0x67, 0x9d, 0x56, 0x56, 0xed, 0xbb, 0x4a, 0xdb, 0x96, 0x74, 0x78, 0xee,
	0x9c, 0x8b, 0xa9, 0x1f, 0xcb, 0x0a, 0xd2, 0xc7, 0x5f, 0x89, 0x39, 0xcc, 0x64, 0xcd, 0xa2, 0x22,
	0xba, 0x58, 0xf2, 0x99, 0xac, 0x71, 0x03, 0x59, 0xa3, 0x44, 0x65, 0xa5, 0x6a, 0xd9, 0xcc, 0xb9,
	0xc3, 0x8c, 0x0c, 0x52, 0xa1, 0x5a, 0x5b, 0x09, 0xcb, 0x62, 0x77, 0x14, 0x46, 0x5c, 0x43, 0x2c,
	0xdf, 0x5e, 0xd9, 0xdc, 0xb9, 0xbd, 0x2c, 0x97, 0x90, 0x72, 0x7a, 0xff, 0x20, 0x63, 0xcb, 0x6b,
	0x58, 0xdc, 0x6b, 0xad, 0x34, 0x22, 0xcc, 0x85, 0xaa, 0xc9, 0x6d, 0x5b, 0x70, 0xa7, 0xb1, 0x80,
	0x55, 0x4d, 0x46, 0x68, 0xd9, 0x8d, 0x56, 0x8e, 0xad, 0xf2, 0x2b, 0x82, 0x8c, 0x93, 0xe9, 0x54,
	0x6b, 0x68, 0xf2, 0x15, 0x97, 0x10, 0x8a, 0xb9, 0xf8, 0xea, 0xb0, 0xde, 0x85, 0xde, 0xbe, 0x25,
	0x0f, 0x00, 0x6e, 0x21, 0xf3, 0xd2, 0xb0, 0xb8, 0x88, 0x27, 0xe1, 0x81, 0xc0, 0x73, 0x48, 0xa8,
	0xff, 0x72, 0xc3, 0xe6, 0x8e, 0xcd, 0x07, 0xd6, 0x15, 0xe2, 0xfe, 0xf4, 0xf0, 0x1d, 0x41, 0xee,
	0xd3, 0x4f, 0xa4, 0x3f, 0xa5, 0x20, 0xdc, 0x43, 0x72, 0xab, 0xa9, 0xb2, 0x84, 0x7f, 0x16, 0x6c,
	0x4e, 0x07, 0x27, 0xf4, 0x2a, 0x4f, 0xfa, 0xc0, 0x73, 0x57, 0x1f, 0x17, 0xb8, 0xa3, 0x86, 0xfe,
	0x1f, 0xd8, 0x42, 0xfc, 0x40, 0xf6, 0x08, 0xfa, 0xa6, 0x69, 0x46, 0xb4, 0xff, 0x9d, 0x93, 0xf4,
	0x4b, 0xe2, 0x6e, 0xd8, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x55, 0x36, 0xc6, 0x80,
	0x02, 0x00, 0x00,
}
