apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket-server
        image: eu.gcr.io/gcic-219917/websocket-server:latest
        imagePullPolicy: Always
        command: [
          "./websocket-server",
          "--selector=static",
          "--server_address=:8080",
        ]
        env:
        - name: DB_HOST
          value: "mongo:27017"
        - name: MICRO_REGISTRY
          value: "kubernetes"
        - name: MICRO_SELECTOR
          value: "static"
        - name: UPDATED_AT
          value: "Sun 19 Sep 2018 14:38:58 GMT"
        ports:
        - containerPort: 9090
          name: websocket-port